### ISSUE TITLE
Can't run the evaluation script in the point 2 of the documentation for Reaching and Grasping Evaluation

### ISSUE THREAD

**Issue by paucarre** [facebookresearch/NGDF#2]
I'm trying to run the `evaluation script` in the point `2` of the documentation for `Reaching and Grasping Evaluation`
When running the script
```
bash scripts/eval/reach_and_grasp/perobj.sh
```
I get the following error
```
Traceback (most recent call last):
  File "/home/ros/NGDF/OMG-Planner/omg_bullet/panda_scene.py", line 109, in main
    scenes = env.get_scenes(hydra_cfg)
  File "/home/ros/NGDF/OMG-Planner/omg/../omg_bullet/envs/acronym_env.py", line 493, in get_scenes
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/ros/NGDF/scripts/eval/reach_and_grasp/../../../data/../data/object_rotations.csv'
```

Where do I get the `data/object_rotations.csv` ?

**Comment by thomasweng15** [comment]
Hi Pau, thank you for raising this issue -- I've updated the instructions in the README [here](https://github.com/facebookresearch/NGDF/blob/main/README.md#grasp-level-set-optimization-evaluation) to include a link to the missing file, here it is as well: [object_rotations.csv](https://drive.google.com/file/d/1wC_dCpVYy3mVQmpFzcyPARWdDoUmsuHU/view?usp=share_link)

**Comment by paucarre** [comment]
Thanks @thomasweng15 ! That fixed that error but now after fixing a few hardcoded paths and wrong depenency versions ( PR coming) I get the following message:
```
plan step 495 wt obs cost 0.4131138839, wt smth cost 0.5459797, wt goal cost 0.8545577, collision pts: 0                                                                                                   
```
And there is this following **error** message:
```
Unknown tag "contact" in /robot[@name='panda']/link[@name='panda_leftfinger']
Unknown tag "contact" in /robot[@name='panda']/link[@name='panda_rightfinger']
```
Debugging I realized that  `self.info` from [OMG-Planner](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L150) is always empy.

This implies that [this line](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L878) nor [this line](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L928) is ever executed.

In fact I had to change the code of `OMG-Planner` to make it work with empty `self.info`. This to me means that it shoudn't be empty in the first place.

I think there is something off. Can you help with that?

**Comment by thomasweng15** [comment]
Hi Pau, you are right that `self.info` shouldn't be empty; however, I do not have an empty `self.info` when I execute the script. 

The [first line](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L878) that you referenced is only executed for baseline methods that use Contact GraspNet (see [this line](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L866) above it).

The second [line](https://github.com/thomasweng15/OMG-Planner/blob/c59b6157693ac22a8818e4e24f6620b9bbaceb3e/omg/planner.py#L928) should be executed when running the NGDF evaluation. `info_t` is returned by the optimization and then appended to `self.info`. Is it possible that in your debugging, the code execution was still in the first loop, so `self.info` was empty before the first `info_t` was appended?

It does seem that you are on the correct commit for OMG-Planner, so that is unlikely to be the issue. If you want to share the modifications you made to get the code running for you, I can take a look, thank you.

**Comment by paucarre** [comment]
I had the wrong `OMG-Planner` commit, my bad! 
It works now :)
